-- RLS smoke tests for a local Supabase database.
-- Prerequisite: migrations + supabase/seed.sql. Run with psql as postgres.
-- The transaction is rolled back, so the database remains unchanged.

begin;

reset role;
insert into public.companies (id, name, slug, status)
values ('30000000-0000-4000-8000-000000000002', 'Másik Demo Kft.', 'masik-demo', 'active');

insert into public.jobs (id, company_id, title, slug, status, short_description, summary)
values
  (
    '40000000-0000-4000-8000-000000000002',
    '30000000-0000-4000-8000-000000000002',
    'Másik cég publikált állása', 'masik-published', 'published', 'Teszt', 'Teszt'
  ),
  (
    '40000000-0000-4000-8000-000000000003',
    '30000000-0000-4000-8000-000000000002',
    'Másik cég draft állása', 'masik-draft', 'draft', 'Teszt', 'Teszt'
  );

insert into public.applications (
  id, job_id, applicant_name, applicant_email, candidate_name, candidate_email,
  consent_accepted, consent_privacy
)
values (
  '60000000-0000-4000-8000-000000000099',
  '40000000-0000-4000-8000-000000000002',
  'Másik Cég Jelentkező', 'masik@example.com',
  'Másik Cég Jelentkező', 'masik@example.com', true, true
);

-- ANON: published data only; private records are never readable.
set local role anon;
set local request.jwt.claims = '{"role":"anon"}';

do $$
begin
  assert (select count(*) from public.jobs where status <> 'published') = 0,
    'anon saw a non-published job';
  assert (select count(*) from public.applications) = 0,
    'anon saw applications';
  assert (select count(*) from public.application_answers) = 0,
    'anon saw application answers';
  assert (select count(*) from public.uploaded_files) = 0,
    'anon saw uploaded file metadata';
end;
$$;

-- ID/timestamps are generated by the database because anon has only column-level grants.
insert into public.applications (
  job_id, applicant_name, applicant_email, candidate_name, candidate_email,
  consent_accepted, consent_privacy, status
)
values (
  '40000000-0000-4000-8000-000000000002',
  'Anon Teszt', 'anon@example.com', 'Anon Teszt', 'anon@example.com',
  true, true, 'new'
);

do $$
begin
  begin
    insert into public.applications (
      job_id, applicant_name, applicant_email, candidate_name, candidate_email,
      consent_accepted, consent_privacy, status
    ) values (
      '40000000-0000-4000-8000-000000000003',
      'Tiltott Teszt', 'tiltott@example.com', 'Tiltott Teszt', 'tiltott@example.com',
      true, true, 'new'
    );
    raise exception 'anon inserted an application for a draft job';
  exception when insufficient_privilege then
    null;
  end;
end;
$$;

-- PARTNER: only own-company rows are visible; updates use the limited RPC.
reset role;
set local role authenticated;
set local request.jwt.claims =
  '{"sub":"20000000-0000-4000-8000-000000000001","role":"authenticated"}';

do $$
begin
  assert (select count(*) from public.companies where id <> '30000000-0000-4000-8000-000000000001') = 0,
    'partner saw another company';
  assert (select count(*) from public.jobs where company_id <> '30000000-0000-4000-8000-000000000001') = 0,
    'partner saw another company job';
  assert (
    select count(*)
    from public.applications a join public.jobs j on j.id = a.job_id
    where j.company_id <> '30000000-0000-4000-8000-000000000001'
  ) = 0, 'partner saw another company application';
end;
$$;

select public.partner_update_application(
  '60000000-0000-4000-8000-000000000001',
  'contacted', 'RLS teszt megjegyzés', now() + interval '1 day', now()
);

do $$
declare
  changed_rows integer;
begin
  update public.applications
  set applicant_email = 'tiltott-modositas@example.com'
  where id = '60000000-0000-4000-8000-000000000001';
  get diagnostics changed_rows = row_count;
  assert changed_rows = 0, 'partner directly updated a protected application column';

  begin
    perform public.partner_update_application(
      '60000000-0000-4000-8000-000000000099',
      'rejected', 'Tiltott', null, now()
    );
    raise exception 'partner updated another company application';
  exception when insufficient_privilege then
    null;
  end;
end;
$$;

-- Equivalent scope to the partner CSV export.
do $$
begin
  assert (
    select count(*)
    from public.applications a join public.jobs j on j.id = a.job_id
    where j.company_id <> '30000000-0000-4000-8000-000000000001'
  ) = 0, 'partner export scope contains another company';
end;
$$;

-- ADMIN: every company and application is visible.
reset role;
set local role authenticated;
set local request.jwt.claims =
  '{"sub":"10000000-0000-4000-8000-000000000001","role":"authenticated"}';

do $$
begin
  assert (select count(*) from public.companies) >= 2,
    'admin cannot see every company';
  assert (select count(*) from public.applications) >= 4,
    'admin cannot see every application';
end;
$$;

rollback;

