import { saveEmailTemplateAction } from "@/app/admin/crm-actions";
import { formatDateTime } from "@/lib/recruitment";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export default async function EmailTemplatePage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const query = await searchParams;
  const supabase = await createServerSupabaseClient();
  const { data: template, error } = await supabase.from("email_templates").select("*").eq("id", "application_confirmation").single();
  if (error || !template) throw new Error(error?.message ?? "Az e-mail-sablon nem található. Futtasd a legfrissebb migrációt.");
  return <><header className="admin-page-header"><div><span className="admin-eyebrow">Automatikus kommunikáció</span><h2>E-mail sablon</h2><p>A sikeres jelentkezés után automatikusan kiküldött visszaigazolás szerkeszthető szövegrészei.</p></div></header>{query.saved === "1" ? <div className="admin-feedback">Az e-mail-sablon sikeresen mentve.</div> : null}<div className="admin-detail-grid"><form action={saveEmailTemplateAction} className="admin-card"><div className="admin-form-section-header"><h3>Visszaigazoló e-mail</h3><p>Utoljára módosítva: {formatDateTime(template.updated_at)}</p></div><div className="admin-form-grid"><label className="admin-field full">Tárgy *<input className="admin-input" defaultValue={template.subject} name="subject" required /></label><label className="admin-field full">Bevezető szöveg *<textarea className="admin-textarea" defaultValue={template.intro_text} name="intro_text" required rows={4} /></label><label className="admin-field full">Következő lépés *<textarea className="admin-textarea" defaultValue={template.next_step_text} name="next_step_text" required rows={4} /></label><label className="admin-field full">Kapcsolattartási adatok *<textarea className="admin-textarea" defaultValue={template.contact_details} name="contact_details" required rows={3} /></label><label className="admin-field full">Aláírás *<textarea className="admin-textarea" defaultValue={template.signature} name="signature" required rows={3} /></label></div><div className="admin-form-footer"><button className="admin-button" type="submit">Sablon mentése</button></div></form><aside className="admin-card"><h3>Kötelező dinamikus tartalom</h3><p style={{ color: "var(--admin-muted)", fontSize: 13, lineHeight: 1.6 }}>A rendszer a szerkeszthető részek közé mindig biztonságosan beszúrja az alábbi adatokat; ezeket innen nem lehet eltávolítani:</p><ul style={{ color: "var(--admin-muted)", lineHeight: 1.9, paddingLeft: 20 }}><li>jelentkező neve és elérhetőségei</li><li>állás és cég neve</li><li>jelentkezés időpontja</li><li>egyedi kérdések és válaszok</li><li>önéletrajz feltöltésének visszajelzése</li><li>adatvédelmi lábléc</li></ul><p style={{ color: "var(--admin-muted)", fontSize: 12 }}>A tárgyban a <code>{"{{job_title}}"}</code> változó kötelező.</p></aside></div></>;
}
